### PR TITLE
Feature/guzzle options

### LINKED ISSUE #2: Add timeout
Please, add timeout option, so that we can control how long the request may work.

### PR DESCRIPTION
**Pull request by rvalitov**
Adds options for Guzzle, for example, now we can configure the request timeout. Closes #2

### CODE REVIEW

**Comment by coderholic** [comment]
Nice PR, thank you!

Instead of being able to pass in Guzzle options, which ties us to Guzzle and requires the developer to be familiar with what Guzzle supports I'd instead like to add some new standard options to the IPinfo constructor (like timeout, and anything else you think it'd be good to support), which we than pass into Guzzle. That way we can support the same options consistently across all of our different libraries (for Python, Java, Ruby etc).

**Comment by rvalitov** [comment]
@coderholic Thank you very much for a prompt feedback. I understand your point, however, the API itself has the standards and that's enough - each library (PHP, Java,...) uses the helper specific language-related functions or classes. In this case it's Guzzle and it's good and well-known for almost all PHP developers (please, keep in mind, that this library is intended for developers, which means they are not afraid of Guzzle 😋). That's why I don't see any benefits when you try to hide the Guzzle options. I believe if you allow to pass the options directly, then you will provide more freedom and make more people happy 😄

Most of the developers use only a single library (for example, I use only PHP), so I don't care for Python, Java or Ruby. But I prefer to have a maximum flexibility of the library I have. So, if someday I will go to Python and there will be a way to improve it and use its full potential, then I don't think it's wise to restrict that only because developers of other libraries don't have similar opportunities/environment/tools or options....

**Comment by coderholic** [comment]
Timeout is such an important setting, that I think it's worth making it first-class, rather than something that you can only configure via guzzle-settings. Doing so makes it clear that it's important, makes it consistent across libraries (not important for the user of a specific library, which is the point you're making, but it's important for *us* as the maintainers of lots of different libraries - the less divergent they are the easier to maintain and reason about, and document), and it means the interface of the library doesn't need to change if we ever want to switch out guzzle for some new-hotness.

**Comment by rvalitov** [comment]
Sounds good. BTW, Guzzle has 3 timeout options... Some developers may need to setup a proxy if their code is working behind a firewall... There are many other scenarios when users need to pass the Guzzle options directly. What I want to say, that if you want to give to the `timeout` option some importance - that's OK, I can understand you idea. But I think users still need the ability to pass the Guzzle options, too - just don't restrict that, please.

**Comment by coderholic** [comment]
Oh sure, should have clarified that - I think the timeout should be a first-class option, but I like the idea of being able to provide other options to guzzle too.

**Comment by rvalitov** [comment]
Thank you for clarification! I had some misunderstanding. Now I completely support your idea:)

**Comment by UmanShahzad** [comment]
Hey @rvalitov , I'm going to add what you and @coderholic discussed above - first-class support for a basic timeout option, and then full custom Guzzle configurability. Closing this in favor of that, unless you want to implement it first :)

**Comment by UmanShahzad** [comment]
#21 will contain this.

**Comment by rvalitov** [comment]
Thank you for mentioning me and the information! I may contribute if you allow me to but not earlier than next week. If you prefer to do it yourself, then no problem 😊

**Comment by UmanShahzad** [comment]
@rvalitov that's alright, the implementation is complete. https://github.com/ipinfo/php/pull/21/commits/316de0b7c09dbd65a8ef836e03311ee2af2d9108

**Pull request closed without merging**
